### PR TITLE
Add Algos

### PR DESCRIPTION
**Pull request by Dustin21**
add hc_som, dbscan, cmeans

### CODE REVIEW

**Comment by AlineTalhouk** [comment]
@Dustin21 please make sure you update the documentation as well.

**Comment by dchiu911** [comment]
Yeah following up on what @AlineTalhouk said, could you please run `devtools::document()` after adding docs on the new `@param`s so we know what they are, values they can take, defaults, etc. Then commit the modified `.Rd` file to this same PR.

**Comment by Dustin21** [comment]
Sounds good and thanks for the helpful command @dchiu911. I'll get on this shortly.

**Comment by Dustin21** [comment]
@dchiu911 The docs have been updated. Let me know how this works.

**Comment by Dustin21** [comment]
hmm, I just tried that and it didn't seem to change anything...

**Comment by dchiu911** [comment]
No worries in that case, I'll try and do it on my end.

**Pull request merged**
